### ISSUE TITLE
리드미 작성

### ISSUE THREAD

**Issue by parkhojeong** [siner308/ttbkk-server#41]
프로젝트 실행을 위한 setup 절차와 script 등이 추가되면 좋을 것 같습니다
https://github.com/siner308/ttbkk-web 실행을 위해 서버를 띄워야하는데 실행방법이 안적혀져있어 요청드립니다!

**Comment by siner308** [comment]
앗 감사합니다! 조만간 다른 분들도 작업하실수있게 정리해두겠습니다

**Comment by siner308** [comment]
@parkhojeong 리드미 작성 완료하였습니다! 추가적으로  필요한 부분이 있다면 요청 부탁드려요~

**Comment by parkhojeong** [comment]
@siner308 
업데이트 해주신 리드미 기반으로 requirements.txt 타겟으로 해서 pip install 했는데 다음과 같은 에러가 나오는데 해결 방법 아실까요?

![image](https://user-images.githubusercontent.com/34734102/161567161-b49fb269-5752-4f52-8d86-f4d4eb0fe2aa.png)
